#Download Manager Configuration
#Fri Dec 19 22:08:20 EET 2025
download.directory=D\:\\DownloadTest
download.maxSpeed=10240000
p2p.central.port=5000
p2p.directory=D\:\\testp2p
p2p.port=5007
p2p.serverAddress=127.0.0.1
